CREATE TABLE IF NOT EXISTS TBLPASSWORDHASHES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDUSER INT,
    HASH VARCHAR(255) NOT NULL,
    FOREIGN KEY (IDUSER) REFERENCES TBLUSERS(ID) ON DELETE CASCADE
);
